### ISSUE TITLE
Erro installing on Windows 7 professional

### ISSUE THREAD

**Issue by gersonfreire** [gersonfreire/JiraAddWork#2]
From review https://marketplace.atlassian.com/plugins/br.com.etaure.ettimer/cloud/reviews
-----
by Arthur Mack on 2017-08-03
Wont even install on Win 7 professional
Flag as inappropriate

ETAURE Time Tracker
Hi Arthur. Indeed, it was developed for Win 8.1 or greater but I intend to release in a few days a new version in order to attend your neeeds ok?

----

ClickOnce installing log file:

---
PLATFORM VERSION INFO
	Windows 			: 6.1.7601.65536 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.6.1099.0 built by: NETFXREL4STAGE
	clr.dll 			: 4.6.1099.0 built by: NETFXREL4STAGE
	dfdll.dll 			: 4.6.1099.0 built by: NETFXREL4STAGE
	dfshim.dll 			: 4.0.41209.0 (Main.041209-0000)

SOURCES
	Deployment url			: http://falcon163.startdedicated.com/etaure/EtTimer2.application
						Server		: Microsoft-IIS/7.5
						X-Powered-By	: ASP.NET
	Deployment Provider url		: http://falcon163.startdedicated.com/etaure/EtTimer2.application
	Application url			: http://falcon163.startdedicated.com/etaure/Application%20Files/EtTimer2_1_2_1_43/EtTimer2.exe.manifest
						Server		: Microsoft-IIS/7.5
						X-Powered-By	: ASP.NET

IDENTITIES
	Deployment Identity		: EtTimer2.application, Version=1.2.1.43, Culture=neutral, PublicKeyToken=651f7a868de687d9, processorArchitecture=msil
	Application Identity		: EtTimer2.exe, Version=1.2.1.43, Culture=neutral, PublicKeyToken=651f7a868de687d9, processorArchitecture=msil, type=win32

APPLICATION SUMMARY
	* Installable application.

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of http://falcon163.startdedicated.com/etaure/EtTimer2.application resulted in exception. Following failure messages were detected:
		+ Culture is not supported.
Parameter name: name
pap is an invalid culture identifier.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	There were no warnings during this operation.

OPERATION PROGRESS STATUS
	* [04/08/2017 11:39:19] : Activation of http://falcon163.startdedicated.com/etaure/EtTimer2.application has started.
	* [04/08/2017 11:39:24] : Processing of deployment manifest has successfully completed.
	* [04/08/2017 11:39:24] : Installation of the application has started.
	* [04/08/2017 11:39:25] : Processing of application manifest has successfully completed.
	* [04/08/2017 11:40:15] : Found compatible runtime version 4.0.30319.
	* [04/08/2017 11:40:15] : Request of trust and detection of platform is complete.

ERROR DETAILS
	Following errors were detected during this operation.
	* [04/08/2017 11:40:19] System.Globalization.CultureNotFoundException
		- Culture is not supported.
Parameter name: name
pap is an invalid culture identifier.
		- Source: mscorlib
		- Stack trace:
			at System.Globalization.CultureInfo..ctor(String name, Boolean useUserOverride)
			at System.Deployment.Application.AssemblyMetaDataImport.ConstructAssemblyName(IntPtr asmMetaPtr, Char[] asmNameBuf, UInt32 asmNameLength, IntPtr pubKeyPtr, UInt32 pubKeyBytes, UInt32 flags)
			at System.Deployment.Application.AssemblyMetaDataImport.ImportIdentity()
			at System.Deployment.Application.AssemblyMetaDataImport.get_Name()
			at System.Deployment.Application.Manifest.AssemblyManifest.LoadFromCompLibAssembly(String filePath)
			at System.Deployment.Application.Manifest.AssemblyManifest.LoadFromInternalManifestFile(String filePath)
			at System.Deployment.Application.DownloadManager.ProcessDownloadedFile(Object sender, DownloadEventArgs e)
			at System.Deployment.Application.FileDownloader.DownloadModifiedEventHandler.Invoke(Object sender, DownloadEventArgs e)
			at System.Deployment.Application.FileDownloader.OnModified()
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
			at System.Deployment.Application.SystemNetDownloader.DownloadAllFiles()
			at System.Deployment.Application.FileDownloader.Download(SubscriptionState subState)
			at System.Deployment.Application.DownloadManager.DownloadDependencies(SubscriptionState subState, AssemblyManifest deployManifest, AssemblyManifest appManifest, Uri sourceUriBase, String targetDirectory, String group, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
			at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.

**Comment by gersonfreire** [comment]
Fixed on version 1.2.2.47
